version: '3.8'

services:
  backend:
    build:
      context: ./todo
      dockerfile: backend/Dockerfile
    container_name: todo_backend_prod
    volumes:
      - db_data:/app/db
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=sqlite:///db/db.sqlite3
      - ALLOWED_HOSTS=localhost,backend,your-domain.com
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/todos/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ./todo/frontend
      dockerfile: Dockerfile
    container_name: todo_frontend_prod
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db_data:
    driver: local 